#version: '3.8'

services:

#-----------------------------------------------------#
#     MARIADB
#-----------------------------------------------------#

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    secrets:
      - db_password.txt
      - db_root_password.txt
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf:/etc/mysql/conf.d
    networks:
      - inception

#-----------------------------------------------------#
#     WORDPRESS
#-----------------------------------------------------#

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception


#-----------------------------------------------------#
#     VOLUMI
#-----------------------------------------------------#

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
  wordpress_data:
    name: wordpress_data
    driver: local

#-----------------------------------------------------#
#     SECRETS
#-----------------------------------------------------#

secrets:
  db_password.txt:
    file: ../secrets/db_password.txt
  db_root_password.txt:
    file: ../secrets/db_root_password.txt

#-----------------------------------------------------#
#     RETE
#-----------------------------------------------------#

networks:
  inception:
    driver: bridge
